### ISSUE TITLE
Support maven repo authentication

### ISSUE THREAD

**Issue by ovaris** [markov/jenkins-maven-metadata-plugin#1]
Either provide a way to insert username & password for repository OR even better use Jenkins pre-configured maven repositories.

**Comment by barclay-reg** [comment]
Hi @markov 

have a look at this pull request
https://github.com/jenkinsci/maven-metadata-plugin/pull/2

Beste Grüße vom Bodensee
Robert

**Comment by markov** [comment]
Thanks @barclay-reg!

I've kind of all but forgotten about this plugin. I'll try to push out a new version with your change soon.

Beste Grüße vom aus Lübeck,
Gesh
